### ISSUE TITLE
Test the application (manually solve the resulting nonogram)

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#110]

**Comment by MaximSmolskiy** [comment]
![Screenshot_20190423-212324.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/1e2f8b11-7bcf-455c-ba18-1768dbaab9bb)
![Screenshot_20190423-212418.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/60c5c357-1a46-49b5-a482-64ef94265a6f)
![image.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/3a8a2fbb-4203-4f33-a17f-98ca1e6828aa)
![image (1).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/aad28d53-b415-4994-b02b-950a6c3a9e2e)
![image (2).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/3cbd2ae1-53db-4fd0-a77a-823c0bf105f1)

**Comment by MaximSmolskiy** [comment]
![Screenshot_20190423-222846.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/a7138ec3-9082-4aea-a39d-0a5304076ee4)
![Screenshot_20190423-223004.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/8d3f7767-ebdf-45f7-a62b-6a9ffa0d09a6)
![image (3).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/8bf0bd8a-afc0-4513-8d5c-426ead35d4bc)
![image (4).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/3cb8079a-0f12-4bde-aab8-15a7ba9e7fa3)
![image (5).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/7dd18d3a-6a4c-4ad2-9798-e06fe5aea20a)

**Comment by MaximSmolskiy** [comment]
![Screenshot_20190423-231628.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/72033274-2799-4958-a1a3-f95ef265b104)

![Screenshot_20190423-231655.png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/f545c6a0-be4d-4ee3-b567-d14848143d06)

![image (6).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/2f018922-2a4f-4e8f-b2b9-34857238eec2)

![image (7).png](https://images.zenhubusercontent.com/5c7bc1ffbb593f1d1bd53b31/82fa430c-5237-49b8-a98e-0303e1b0d8e0)

**Comment by maik-nack** [comment]
![image.png](https://images.zenhubusercontent.com/5c7bc255b597e56ca5ef99a0/74a0d8df-2b1f-4dff-a0d5-a751dda71747)
