### ISSUE TITLE
Compare with analogues and describe the advantages over them in README.md

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#22]

**Comment by mashaverdina** [comment]
analogues (sites) -> web analogues or web applications
Does not require internet -> Does not require internet connection 
User can save nonogram and its *miniature* -> *thumbnail*

`Better functionality` is not really correct. Let's move `User can take a photo directly in the application` up to 1 level and use word "Allows to" in the text. Then we can change `better functionality` to `Unique features` or smth like that.
