### ISSUE TITLE
Research about Android version distribution

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#44]

**Comment by Chopikov** [comment]
https://droidbug.com/statistika-raspredeleniya-versiy-os-android-za-oktyabr-2018/
Статистика на октябрь 2018: 89% пользуются Anroid 5.0 и выше
https://androidinsider.ru/os/samyiy-populyarnyiy-android-sentyabrya-2018-goda.html
Сентябрь 2018: 88,5% на 5.0 и выше
