### ISSUE TITLE
Find information about github functionality

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#67]
How to use github correctly in joint project development:
1) How to create your own branches correctly?
2) How to commit correctly?
3) How to push correctly?
4) How to merge branches and pull requests?

All this is necessary so that each member of the team could independently interact with the github and not slow down the development process

**Comment by Chopikov** [comment]
Разница между Rebase и Merge
https://www.quora.com/What-is-the-difference-between-rebase-and-merge-in-Git

**Comment by Chopikov** [comment]
Squash, rebase и merge: примеры, когда нужно использовать каждый из вариантов
https://habr.com/ru/post/337302/

**Comment by Chopikov** [comment]
Решение конфликтов при слиянии
https://habr.com/ru/post/323234/ - как отобразить конфликтные места, чтобы исправить все вручную
https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git - почти то же, что и первое, но еще пара полезных вещей
https://dev.to/nishina555/how-to-ignore-files-already-managed-with-git-locally-19oo - как скрыть локальные изменения

**Comment by Chopikov** [comment]
If on the other hand you want to keep the local modifications somehow, you'd use stash to hide them away before pulling, then reapply them afterwards:

git stash
git pull
git stash pop
