### ISSUE TITLE
Split the README.md into several files

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#68]

**Comment by mashaverdina** [comment]
I thought about several file for developers only (smth like Developers.md or Development.md) with coding standard, git workflow etc. What do you think @MaximSmolskiy?

**Comment by MaximSmolskiy** [comment]
@mashaverdina This is a good idea. Probably it wasn't really worth creating too small separate files for git workflow and rules of commits.
