### ISSUE TITLE
Think about improving the image converting

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#72]

**Comment by maik-nack** [comment]
Using Floyd–Steinberg dithering: 
[Wikipedia](https://en.wikipedia.org/wiki/Dither)
[Implementation on Java](https://stackoverflow.com/questions/5940188/how-to-convert-a-24-bit-png-to-3-bit-png-using-floyd-steinberg-dithering/5940260#5940260) (easy to remake for android)

**Comment by maik-nack** [comment]
Using different color differences:
[Wikipedia](https://en.wikipedia.org/wiki/Color_difference)

I tried `Euclidean` and `CIE76`

**Comment by maik-nack** [comment]
Tried different parameters for Otsu's thresholding and another thresholding from OpenCV. Also, I found this [link](http://recog.ru/blog/applied/15.html).

**Comment by maik-nack** [comment]
After I surfed the Internet, it seems to me that Otsu's thresholding is a good option. If we decide to use it and will not use anything else from the OpenCV, then it can be implemented by yourself.
