### ISSUE TITLE
Think about changing backend

### ISSUE THREAD

**Issue by MaximSmolskiy** [nonoteam/NonoConverter#97]

**Comment by maik-nack** [comment]
Class `Field`
This class exists now. 

Add fields:
* int[] _colors - an array of colors that used in a puzzle. All cells of the field contain values of colors. But now it will contain indexes of these colors in the array `_colors` `by default`.
* int _colorsCount - the length of the array `_colors` (optional).
* int _state - an identifier that indicates what is stored in the field's cells. Both colors and indexes of these colors can be stored in the cells.

Add methods:
* int getLength(int type) - method for call `getRows()` or `getCols()` by the type of a line - row or column.
* int getColor(int i, int j, int type) - method for call `getColor(int, int)` by the type of a line - row or column.
* void setColor(int i, int j, int color, int type) - method for call `setColor(int, int, int)` by the type of a line - row or column.
* int getColors() - method for getting count of colors.
* Bitmap getBitmap() - method for getting thumbnail from Field (cell of the field converts in the pixel of the bitmap).
* void clear() - method for clearing field - all cells loss colors.
* Field translateToColors() - method for getting new field with colors in cells.

Add private constructor without parameters.
Constructor by a count of rows and columns replaced by constructor by a count of rows and columns, bitmap and parameter for converting.

**Comment by maik-nack** [comment]
Class `Nonogram`
This class exists now. 

Add fields:
* Field _field - the field of the puzzle.

Add methods:
* int getFirstLength(int type) - method for call `getLeftRowsLength()` or `getTopColsLength()` by the type of a line - row or column.
* int getSecondLength(int i, int type) - method for call `getLeftRowLength(int)` or `getTopColLength(int)` by the type of a line - row or column.
* int getValue(int i, int j, int type) - method for call `getLeftRowValue(int, int)` or `getTopColValue(int, int)` by the type of a line - row or column.
* boolean checkCorrectness() - method for checking correctness of filling of the field.
* Field getField() - method for getting field of the puzzle.
* void clearField() - method for clearing field of the puzzle (optional).
* Nonogram translateToColors() - method for getting new nonogram that contains field with colors in cells.

Add private constructor without parameters.
Add constructor by a count of rows and columns, bitmap and parameter for converting.

**Comment by maik-nack** [comment]
For more information about `methods by the type of a line` see #87 issue.

**Comment by maik-nack** [comment]
Class `Cell`.
New class. This is the class of the cell of matrix that uses in the algorithm with finite-state machine. 

Fields: 
* int[][] _dirs (or _vals) - this is the array that contains all directions with their values for concrete cell of the matrix. One direction with value is int[2],  where int[0] is direction and int[1] is value. (value = color or index of color). 

Methods: 
* void addDirection(int dir,  int val) - method for adding new direction with value for it. 
* boolean isEqualVals() - this method returns `true` in case if all int[][1] equals. If length of `_dirs` is zero this method returns `false`.
* int[][] getDirs() - method for getting array of directions with their values. 

Constructor without parameters.

**Comment by maik-nack** [comment]
Class `StateMachine`.
New class. This is the representation of the finite-state machine. It contains state table. 

Fields: 
* int[][] _table - state table. Rows - states,  columns - input data - indexes of colors.
* int _states - count of states

Methods: 
* int getNextState(int state,  int input) - method for getting state we can go to from `state`,  if input value is `input`
* int getStates() - method for getting count of states. 

Contructor by the line (int[] line) - numbers from nonogram.

**Comment by maik-nack** [comment]
Class `NonogramSolver`.
This class exists now. 

Fields: 
* Nonogram _nono - nonogram that could be solved. 
* AsyncTask<Void,  Void,  Nonogram> _asynkTask - AsyncTask for converting image. 
* HashSet<Integer> _rows,  _cols - sets for storage numbers of rows and columns that must be processed. 
* HashSet<Integer> _states - set for storage numbers of states of state machine for algorithm that uses finite-state machine. 
* StateMachine[] _rowsFSM, _colsFSM - finite-state machines for nonogram. 

Methods: 
* void setNonogram(Nonogram nono) 
* void setAsyncTask(AsyncTask<Void,  Void,  Nonogram> asynkTask) 
* void init() - initialize state of solver before starting to solve. 
* boolean solve()  - method for solving puzzle. It returns `true` if nonogram can be solved. 
* boolean applySimpleBoxes(int i, int type) - method for applying algorithm `Simple boxes` for line with index `i` with type `type` (row or column). 
* boolean applyStateMachine(int i, int type) - method for applying algorithm with finite-state machine for line with index `i` with type `type` (row or column). It returns `false` if this nonogram hasn't solution. 

Constructor without parameters.

**Comment by maik-nack** [comment]
Class `ImageConverter`.
This class exists now.

Replace method 
```java
    public static Field convertImage(
            Bitmap bmp,
            int rows,
            int cols,
            AsyncTask<Void, Void, Field> asyncTask)
```
by 
```java
    public static Nonogram convertImage(
            Bitmap bmp,
            int rows,
            int cols,
            AsyncTask<Void, Void, Nonogram> asyncTask)
```

Move method `getThumbnail` in the constructor of `Field` class.
